frr version 10.5.1
frr defaults traditional
hostname r1
no ipv6 forwarding
!
interface eth1
 description R1-TO-R2
 ip address 10.0.12.1/30
 ip ospf cost 10
 ip ospf network point-to-point
!
interface eth2
 description R1-TO-R3-BACKUP
 ip address 10.0.13.1/30
 ip ospf cost 80
 ip ospf network point-to-point
!
interface eth3
 description R1-TO-CLIENT
 ip address 192.168.10.1/24
!
interface lo
 ip address 1.1.1.1/32
!
router ospf
 ospf router-id 1.1.1.1
 passive-interface eth3
 network 1.1.1.1/32 area 0.0.0.0
 network 10.0.12.0/30 area 0.0.0.0
 network 10.0.13.0/30 area 0.0.0.0
 network 192.168.10.0/24 area 0.0.0.0
!
line vty
!
